/*
 * THIS FILE IS AUTO-GENERATED BY 'smart-i18n-react'
 * DO NOT EDIT THIS FILE MANUALLY.
 * ...
 * 
 */

export const languages = ["kk","ru","en"] as const;
export type TLanguage = (typeof languages)[number];
export const FALLBACK_LANGUAGE: TLanguage = "en";
export const defaultNS = "translation";
export const COOKIE_NAME = "NEXT_LANGUAGE";