export const GENERATED_CONFIG_PATH = 'src/i18n/generated/config.ts';
export const GENERATED_NAMESPACES_PATH = 'src/i18n/generated/namespaces.ts';
export const GENERATED_LOCALES_PATH = 'src/i18n/locales';
export const GENERATED_TYPES_PATH = 'src/i18n/generated/types.ts';
export const COOKIE_NAME = "I18NEXT_LANGUAGE";
export const AUTOGENERATION_COMMENT = `
/*
 * THIS FILE IS AUTO-GENERATED BY 'smart-i18next-cli'
 * DO NOT EDIT THIS FILE MANUALLY.
 * ...
 * 
 */
`.trim();
